name: GravityLog
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.8.3
  - numpy=1.26.4
  - pandas=2.2.1
  - plotly=5.22.0
  - python=3.11.2
  - seaborn=0.13.2
  - scikit-learn=1.5.1
  - streamlit=1.41.1
  - watchdog=6.0.0
