[client]
showSidebarNavigation = false

[server]
runOnSave = true
headless = true

[theme]
# Primary accent for interactive elements
primaryColor = '#40A2E3'

# Background color for the main content area
backgroundColor = '#FFFCE9'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#BBE2EC'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "monospace"
